<?php

namespace Database\Seeders;

use App\Models\CategoriaFiscal;
use Illuminate\Database\Seeder;

class CategoriaFiscalDadosOperacionaisSeeder extends Seeder
{
    private const DEFAULT_OBSERVATION = 'Categoria fiscal ativada com dados aproximados para operacao inicial. Validar CSOSN, PIS/COFINS, IBS/CBS, cClassTrib, beneficios, ST e regras estaduais com contador antes do uso definitivo.';

    public function run(): void
    {
        foreach ($this->categories() as $category) {
            CategoriaFiscal::updateOrCreate(
                ['tb30_codigo' => $category['tb30_codigo']],
                array_merge([
                    'tb30_ativo' => true,
                    'tb30_data_inicio_vigencia' => now()->toDateString(),
                    'tb30_data_fim_vigencia' => null,
                    'tb30_cfop_venda_interestadual' => null,
                    'tb30_cst_icms' => null,
                    'tb30_cst_pis' => '49',
                    'tb30_cst_cofins' => '49',
                    'tb30_cst_ibs' => '000',
                    'tb30_cst_cbs' => '000',
                    'tb30_cclass_trib' => '000001',
                    'tb30_aliquota_icms' => 0,
                    'tb30_aliquota_pis' => 0,
                    'tb30_aliquota_cofins' => 0,
                    'tb30_aliquota_ibs_uf' => 0.05,
                    'tb30_aliquota_ibs_municipio' => 0.05,
                    'tb30_aliquota_cbs' => 0.9,
                    'tb30_aliquota_is' => 0,
                    'tb30_natureza_receita' => 'Venda NFC-e Simples Nacional',
                    'tb30_observacao_fiscal' => self::DEFAULT_OBSERVATION,
                ], $category)
            );
        }
    }

    private function categories(): array
    {
        return [
            [
                'tb30_codigo' => 'PANIFICACAO_PROPRIA',
                'tb30_nome' => 'PANIFICACAO PROPRIA',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_FABRICACAO_PROPRIA,
                'tb30_cfop_venda_interna' => '5101',
                'tb30_cfop_venda_interestadual' => '6101',
                'tb30_cfop_consumo_local' => '5101',
                'tb30_cfop_entrega' => '5101',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'PRODUCAO PROPRIA SIMPLES',
            ],
            [
                'tb30_codigo' => 'CONFEITARIA_PROPRIA',
                'tb30_nome' => 'CONFEITARIA PROPRIA',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_FABRICACAO_PROPRIA,
                'tb30_cfop_venda_interna' => '5101',
                'tb30_cfop_venda_interestadual' => '6101',
                'tb30_cfop_consumo_local' => '5101',
                'tb30_cfop_entrega' => '5101',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'PRODUCAO PROPRIA SIMPLES',
            ],
            [
                'tb30_codigo' => 'SALGADOS_PROPRIOS',
                'tb30_nome' => 'SALGADOS PROPRIOS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_FABRICACAO_PROPRIA,
                'tb30_cfop_venda_interna' => '5101',
                'tb30_cfop_venda_interestadual' => '6101',
                'tb30_cfop_consumo_local' => '5101',
                'tb30_cfop_entrega' => '5101',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'PRODUCAO PROPRIA SIMPLES',
            ],
            [
                'tb30_codigo' => 'BEBIDAS_PREPARADAS',
                'tb30_nome' => 'BEBIDAS PREPARADAS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_PREPARO_MONTAGEM,
                'tb30_cfop_venda_interna' => '5101',
                'tb30_cfop_venda_interestadual' => '6101',
                'tb30_cfop_consumo_local' => '5101',
                'tb30_cfop_entrega' => '5101',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'PREPARO MONTAGEM VALIDAR',
                'tb30_observacao_fiscal' => 'Categoria de bebidas preparadas ativada com dados aproximados. Separar bebida preparada de bebida industrializada comprada pronta. Validar CFOP, CSOSN, PIS/COFINS, IBS/CBS e cClassTrib com contador.',
            ],
            [
                'tb30_codigo' => 'LANCHES_MONTAGEM',
                'tb30_nome' => 'LANCHES E MONTAGEM',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_PREPARO_MONTAGEM,
                'tb30_cfop_venda_interna' => '5101',
                'tb30_cfop_venda_interestadual' => '6101',
                'tb30_cfop_consumo_local' => '5101',
                'tb30_cfop_entrega' => '5101',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'PREPARO MONTAGEM SIMPLES',
            ],
            [
                'tb30_codigo' => 'REVENDA_ALIMENTICIA_IND',
                'tb30_nome' => 'REVENDA ALIMENTICIA INDUSTRIALIZADA',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA SIMPLES',
            ],
            [
                'tb30_codigo' => 'REVENDA_MASSAS_MACARRAO',
                'tb30_nome' => 'REVENDA MASSAS E MACARRAO',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Macarrao, massas secas, massas instantaneas e similares comprados para revenda.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA MERCEARIA VALIDAR',
                'tb30_observacao_fiscal' => 'Massas e macarrao de revenda ativados com dados aproximados. Validar NCM, CEST, ST, PIS/COFINS e IBS/CBS com XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_BISCOITOS_BOLACHAS',
                'tb30_nome' => 'REVENDA BISCOITOS E BOLACHAS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Biscoitos doces, salgados, recheados, wafers, cookies e similares para revenda.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA MERCEARIA VALIDAR',
                'tb30_observacao_fiscal' => 'Biscoitos e bolachas de revenda ativados com dados aproximados. Conferir NCM, CEST, ST e regras especificas pelo XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_ACHOCOLATADOS',
                'tb30_nome' => 'REVENDA ACHOCOLATADOS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Achocolatado em po, bebida achocolatada pronta, creme de chocolate e similares.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA MERCEARIA VALIDAR',
                'tb30_observacao_fiscal' => 'Achocolatados de revenda ativados com dados aproximados. O NCM pode mudar entre po, bebida pronta e creme. Validar XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_DOCES_CHOCOLATES_GOMAS',
                'tb30_nome' => 'REVENDA DOCES CHOCOLATES E GOMAS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Barras de chocolate, bombons, balas, pirulitos, chicletes, gomas e doces embalados.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA DOCES VALIDAR',
                'tb30_observacao_fiscal' => 'Doces, chocolates, balas, pirulitos, chicletes e gomas de revenda ativados com dados aproximados. Validar NCM, CEST, ST, PIS/COFINS, IBS/CBS e XML do fornecedor com contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_MERCEARIA_SECA',
                'tb30_nome' => 'REVENDA MERCEARIA SECA',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Arroz, feijao, acucar, farinha, oleo, enlatados, condimentos e mercearia seca em geral.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA MERCEARIA VALIDAR',
                'tb30_observacao_fiscal' => 'Mercearia seca ativada com dados aproximados. Validar produto por produto pelo XML do fornecedor, pois NCM, CEST, ST e beneficios podem variar.',
            ],
            [
                'tb30_codigo' => 'REVENDA_BEBIDAS',
                'tb30_nome' => 'REVENDA DE BEBIDAS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA BEBIDAS VALIDAR ST',
                'tb30_observacao_fiscal' => 'Bebidas de revenda ativadas com dados aproximados. Algumas bebidas podem ter ICMS-ST, CEST e CFOP/CSOSN especificos. Usar XML do fornecedor e validacao do contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_AGUA_MINERAL',
                'tb30_nome' => 'REVENDA AGUA MINERAL',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Agua mineral, agua natural e agua com gas compradas prontas para revenda.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA BEBIDA VALIDAR ST',
                'tb30_observacao_fiscal' => 'Agua mineral de revenda ativada com dados aproximados. Validar NCM, CEST, ICMS-ST, beneficio fiscal, PIS/COFINS e IBS/CBS com XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_REFRIGERANTES',
                'tb30_nome' => 'REVENDA REFRIGERANTES',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Refrigerantes em lata, garrafa ou outras embalagens comprados prontos para revenda.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA BEBIDA VALIDAR ST',
                'tb30_observacao_fiscal' => 'Refrigerantes de revenda ativados com dados aproximados. Bebidas podem ter ICMS-ST, CEST e regras especificas. Conferir XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_ENERGETICOS_ISOTONICOS',
                'tb30_nome' => 'REVENDA ENERGETICOS E ISOTONICOS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Energeticos, isotonicos e bebidas funcionais compradas prontas para revenda.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA BEBIDA VALIDAR ST',
                'tb30_observacao_fiscal' => 'Energeticos e isotonicos de revenda ativados com dados aproximados. Validar NCM, CEST, ICMS-ST, PIS/COFINS, IBS/CBS e possiveis regras especificas com contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_SUCOS_PRONTOS',
                'tb30_nome' => 'REVENDA SUCOS PRONTOS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Sucos, nectares, refrescos, chas prontos e bebidas nao alcoolicas industrializadas.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA BEBIDA VALIDAR ST',
                'tb30_observacao_fiscal' => 'Sucos e bebidas prontas de revenda ativados com dados aproximados. Validar NCM especifico, CEST, ST e tributacao pelo XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_LEITE',
                'tb30_nome' => 'REVENDA LEITE',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Leite UHT, pasteurizado, integral, desnatado, semidesnatado e zero lactose comprados para revenda.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA LATICINIO VALIDAR BENEFICIO',
                'tb30_observacao_fiscal' => 'Leite de revenda ativado com dados aproximados. Pode haver beneficio fiscal, reducao, isencao ou regra estadual especifica. Conferir XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_IOGURTES_BEBIDAS_LACTEAS',
                'tb30_nome' => 'REVENDA IOGURTES E BEBIDAS LACTEAS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Iogurtes, bebidas lacteas, achocolatados lacteos e similares comprados para revenda.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA LATICINIO VALIDAR',
                'tb30_observacao_fiscal' => 'Iogurtes e bebidas lacteas de revenda ativados com dados aproximados. Validar NCM, CEST, beneficios, ST, PIS/COFINS e IBS/CBS com XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_REFRIG_CONGELADA',
                'tb30_nome' => 'REVENDA REFRIGERADA OU CONGELADA',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA VALIDAR ST',
                'tb30_observacao_fiscal' => 'Produtos refrigerados ou congelados de revenda ativados com dados aproximados. Variam por NCM, CEST e ST. Usar XML do fornecedor e validacao do contador.',
            ],
            [
                'tb30_codigo' => 'FRIOS_LATICINIOS_FRACIONADOS',
                'tb30_nome' => 'FRIOS E LATICINIOS FRACIONADOS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_PREPARO_MONTAGEM,
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'FRACIONAMENTO VALIDAR',
                'tb30_observacao_fiscal' => 'Frios e laticinios ativados com dados aproximados. Podem ser revenda, fracionamento ou preparo. Validar CFOP, CSOSN, ST, PIS/COFINS, IBS/CBS e cClassTrib com contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_SABOES_DETERGENTES',
                'tb30_nome' => 'REVENDA SABOES E DETERGENTES',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Sabao em po, sabao em barra, detergente, lava roupas e produtos similares de limpeza.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA LIMPEZA VALIDAR ST',
                'tb30_observacao_fiscal' => 'Saboes e detergentes de revenda ativados com dados aproximados. Produtos de limpeza podem ter CEST/ST e NCM especifico. Conferir XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_AGUA_SANITARIA_DESINFETANTES',
                'tb30_nome' => 'REVENDA AGUA SANITARIA E DESINFETANTES',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Agua sanitaria, desinfetante, multiuso, limpadores e saneantes domesticos.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA LIMPEZA VALIDAR ST',
                'tb30_observacao_fiscal' => 'Agua sanitaria, desinfetantes e saneantes ativados com dados aproximados. Validar NCM, CEST, ST e regras especificas com XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_HIGIENE_PESSOAL',
                'tb30_nome' => 'REVENDA HIGIENE PESSOAL',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Creme dental, sabonete, shampoo, condicionador, absorvente, desodorante e higiene pessoal em geral.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA HIGIENE VALIDAR ST',
                'tb30_observacao_fiscal' => 'Higiene pessoal de revenda ativada com dados aproximados. Validar NCM, CEST, ST, monofasico/PIS-COFINS quando aplicavel, XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'REVENDA_PAPEL_HIGIENICO_DESCARTAVEIS',
                'tb30_nome' => 'REVENDA PAPEL HIGIENICO E DESCARTAVEIS',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_descricao' => 'Papel higienico, papel toalha, guardanapos, copos, pratos, talheres e embalagens descartaveis.',
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVENDA DESCARTAVEIS VALIDAR',
                'tb30_observacao_fiscal' => 'Papel higienico e descartaveis ativados com dados aproximados. Validar NCM, CEST, ST e regras por produto com XML do fornecedor e contador.',
            ],
            [
                'tb30_codigo' => 'ANALISE_FISCAL_INDIVIDUAL',
                'tb30_nome' => 'ANALISE FISCAL INDIVIDUAL',
                'tb30_origem_mercadoria' => CategoriaFiscal::ORIGEM_REVENDA,
                'tb30_cfop_venda_interna' => '5102',
                'tb30_cfop_venda_interestadual' => '6102',
                'tb30_cfop_consumo_local' => '5102',
                'tb30_cfop_entrega' => '5102',
                'tb30_csosn' => '102',
                'tb30_regra_icms' => 'REVISAO FISCAL INDIVIDUAL',
                'tb30_observacao_fiscal' => 'Categoria ativada com dados aproximados apenas para permitir associacao inicial. Revisar produto a produto com contador antes de emitir nota.',
            ],
        ];
    }
}
